"""Deterministic reference pages; no optional document backends are loaded."""

import argparse
import inspect
import json
from pathlib import Path

from textalchemy.__main__ import _setup_parser
from textalchemy.core.registry import all_operations
from textalchemy.pipeline import register_builtin_operations

ROOT = Path(__file__).resolve().parents[2]
NOTICE = "<!-- Generated by uv run python -m tools.docs generate; do not edit. -->\n\n"


def operations():
    register_builtin_operations()
    entries = sorted(all_operations(), key=lambda operation: operation.id)
    lines = [
        "# Операции конвейера",
        "",
        "Справочник формируется из реестра и сигнатур. [Работа с конвейером](../guide/index.md#автоматизация).",
        "",
        "Имя входа ниже — фактический контракт реестра; параметры Python приведены отдельно. "
        "Пути/модели сериализуются runner. Возможные несоответствия явно отмечены.",
        "",
        "| Операция | Вход → выход | Параметр входа |",
        "|---|---|---|",
    ]
    mismatches = []
    for operation in entries:
        if operation.input_param not in inspect.signature(operation.func).parameters:
            mismatches.append(operation.id)
        lines.append(f"| `{operation.id}` | `{operation.input_type}` → `{operation.output_type}` | `{operation.input_param}` |")
    if mismatches:
        lines += [
            "",
            "## Несоответствия контрактов",
            "",
            "У следующих операций вход реестра отсутствует в сигнатуре: " + ", ".join(f"`{op}`" for op in mismatches) + ".",
            "Проверьте `input_param` регистрации и имя аргумента функции перед связыванием шагов через `input`.",
            "",
        ]
    lines += ["", "## Параметры", "", "Все вызовы используют именованные параметры. Значения без `=` обязательны.", ""]
    for operation in entries:
        lines += [
            f"### {operation.id}",
            "",
            operation.description,
            "",
            "```text",
            f"{operation.func.__name__}{inspect.signature(operation.func)}",
            "```",
            "",
        ]
    return NOTICE + "\n".join(lines)


def cli():
    parser = _setup_parser()
    sub = next(action for action in parser._actions if isinstance(action, argparse._SubParsersAction))
    lines = [
        "# Справочник CLI",
        "",
        "Сформирован из парсера команд. Префикс: `uv run textalchemy`. "
        "[Сценарии и ограничения](../guide/index.md#справочник-команд). "
        "Наличие аргумента в парсере не подтверждает его поддержку; статус CLI — [M0](../../TODO.md#m0).",
        "",
    ]
    for name, current in [("Глобальные параметры", parser), *sorted(sub.choices.items())]:
        lines += [f"## {name}", "", "| Аргумент | Назначение | Значение по умолчанию / варианты |", "|---|---|---|"]
        for action in current._actions:
            if isinstance(action, argparse._SubParsersAction) or action.help == argparse.SUPPRESS:
                continue
            label = ", ".join(action.option_strings) or action.dest
            help_text = (action.help or "").replace("|", "&#124;")
            details = []
            if action.required:
                details.append("обязательный")
            if action.default is not None and action.default != argparse.SUPPRESS:
                details.append("default: " + repr(action.default))
            if action.choices is not None:
                details.append("варианты: " + ", ".join(map(str, action.choices)))
            lines.append(f"| `{label}` | {help_text} | {'; '.join(details)} |")
        lines.append("")
    return NOTICE + "\n".join(lines)


def pages():
    from tools.documentation.navigator import code_pages, user_guide

    return {"docs/reference/operations.md": operations(), "docs/reference/cli.md": cli(),
            "docs/reference/user-guide.md": user_guide(ROOT, NOTICE), **code_pages(ROOT, NOTICE)}


def sync(*, check=False):
    stale = []
    for name, content in pages().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if stale and check:
        raise ValueError("Устарели справочники: " + ", ".join(stale) + ". Выполните uv run python -m tools.docs generate")
    return stale


if __name__ == "__main__":
    print(json.dumps(pages()))
